export const mockData = [
  {
    id: "4",
    parentId: "2",
    authorId: "3",
    text: "Some text",
    createdAt: "2024-08-17T13:47:49.277Z",
    children: [],
    author: {
      id: "3",
      username: "John Doe",
      email: "john.doe@example.com",
      createdAt: "2024-08-17T11:59:08.542Z",
    },
  },
  {
    id: "3",
    parentId: "2",
    authorId: "5",
    text: "<h2>Over fact all son tell this any his</h2><p>He as compliment unreserved projecting. Between had observe pretend delight for believe. Do newspaper questions consulted sweetness do. Our sportsman his unwilling fulfilled departure law. Now world own total saved above her cause table. Wicket myself her square remark the should far secure sex. Smiling cousins warrant law explain for whether.</p><p>Far quitting dwelling graceful the likewise received building. An fact so to that show am shed sold cold. Unaffected remarkably get yet introduced excellence terminated led. Result either design saw she esteem and. On ashamed no inhabit ferrars it ye besides resolve. Own judgment directly few trifling. Elderly as pursuit at regular do parlors. Rank what has into fond she.</p><p>Needed feebly dining oh talked wisdom oppose at. Applauded use attempted strangers now are middleton concluded had. It is tried ﻿no added purse shall no on truth. Pleased anxious or as in by viewing forbade minutes prevent. Too leave had those get being led weeks blind. Had men rose from down lady able. Its son him ferrars proceed six parlors. Her say projection age announcing decisively men. Few gay sir those green men timed downs widow chief. Prevailed remainder may propriety can and.</p><p>Throwing consider dwelling bachelor joy her proposal laughter. Raptures returned disposed one entirely her men ham. By to admire vanity county an mutual as roused. Of an thrown am warmly merely result depart supply. Required honoured trifling eat pleasure man relation. Assurance yet bed was improving furniture man. Distrusts delighted she listening mrs extensive admitting far.</p><p>Started several mistake joy say painful removed reached end. State burst think end are its. Arrived off she elderly beloved him affixed noisier yet. An course regard to up he hardly. View four has said does men saw find dear shy. Talent men wicket add garden.</p><p>Far concluded not his something extremity. Want four we face an he gate. On he of played he ladies answer little though nature. Blessing oh do pleasure as so formerly. Took four spot soon led size you. Outlived it received he material. Him yourself joy moderate off repeated laughter outweigh screened.</p><p>Out believe has request not how comfort evident. Up delight cousins we feeling minutes. Genius has looked end piqued spring. Down has rose feel find man. Learning day desirous informed expenses material returned six the. She enabled invited exposed him another. Reasonably conviction solicitude me mr at discretion reasonable. Age out full gate bed day lose.</p><p>Still court no small think death so an wrote. Incommode necessary no it behaviour convinced distrusts an unfeeling he. Could death since do we hoped is in. Exquisite no my attention extensive. The determine conveying moonlight age. Avoid for see marry sorry child. Sitting so totally forbade hundred to.</p><p>You vexed shy mirth now noise. Talked him people valley add use her depend letter. Allowance too applauded now way something recommend. Mrs age men and trees jokes fancy. Gay pretended engrossed eagerness continued ten. Admitting day him contained unfeeling attention mrs out.</p>",
    createdAt: "2024-08-17T13:37:52.930Z",
    children: [],
    author: {
      id: "5",
      username: "John Doe",
      email: "john.doe@example.com",
      createdAt: "2024-08-17T13:37:52.846Z",
    },
  },
  {
    id: "2",
    parentId: null,
    authorId: "4",
    text: "Some text",
    createdAt: "2024-08-17T12:00:01.392Z",
    children: [
      {
        id: "4",
        parentId: "2",
        authorId: "3",
        text: "Some text text",
        createdAt: "2024-08-17T13:47:49.277Z",
        children: [
          {
            id: "5",
            parentId: "4",
            authorId: "3",
            text: "Some text",
            createdAt: "2024-08-17T13:47:49.277Z",
            children: [],
            author: {
              id: "3",
              username: "John Doe",
              email: "john.doe@example.com",
              createdAt: "2024-08-17T11:59:08.542Z",
            },
          },
        ],
        author: {
          id: "3",
          username: "John Doe",
          email: "john.doe@example.com",
          createdAt: "2024-08-17T11:59:08.542Z",
        },
      },
      {
        id: "3",
        parentId: "2",
        authorId: "5",
        text: "Some text",
        createdAt: "2024-08-17T13:37:52.930Z",
        children: [],
        author: {
          id: "3",
          username: "John Doe",
          email: "john.doe@example.com",
          createdAt: "2024-08-17T11:59:08.542Z",
        },
      },
    ],
    author: {
      id: "4",
      username: "John Doe",
      email: "john.doe@example.com",
      createdAt: "2024-08-17T12:00:01.321Z",
    },
  },
  {
    id: "1",
    parentId: null,
    authorId: "3",
    text: "Some text",
    createdAt: "2024-08-17T11:59:08.621Z",
    children: [],
    author: {
      id: "3",
      username: "John Doe",
      email: "john.doe@example.com",
      createdAt: "2024-08-17T11:59:08.542Z",
    },
  },
];
